//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsBVRD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BIEntities : DbContext
    {
        public BIEntities()
            : base("name=BIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vConsultaOrdenesFirme> vConsultaOrdenesFirme { get; set; }
        public DbSet<vUsuarios> vUsuarios { get; set; }
        public DbSet<VOPERACIONES> VOPERACIONES { get; set; }
        public DbSet<vConsultaEmisionesWEB> vConsultaEmisionesWEB { get; set; }
        public DbSet<VOrdenesFirmePropias> VOrdenesFirmePropias { get; set; }
    
        public virtual ObjectResult<WS_AUTENTICARUSUARIO_Result> WS_AUTENTICARUSUARIO(string uSUARIO, string cLAVE, Nullable<int> sERVICIOID)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var sERVICIOIDParameter = sERVICIOID.HasValue ?
                new ObjectParameter("SERVICIOID", sERVICIOID) :
                new ObjectParameter("SERVICIOID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WS_AUTENTICARUSUARIO_Result>("WS_AUTENTICARUSUARIO", uSUARIOParameter, cLAVEParameter, sERVICIOIDParameter);
        }
    
        public virtual ObjectResult<WS_VALIDARTOKEN_Result> WS_VALIDARTOKEN(string tOKEN, Nullable<int> sERVICIOID)
        {
            var tOKENParameter = tOKEN != null ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(string));
    
            var sERVICIOIDParameter = sERVICIOID.HasValue ?
                new ObjectParameter("SERVICIOID", sERVICIOID) :
                new ObjectParameter("SERVICIOID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WS_VALIDARTOKEN_Result>("WS_VALIDARTOKEN", tOKENParameter, sERVICIOIDParameter);
        }
    
        public virtual ObjectResult<WS_OPERACIONES_Result> WS_OPERACIONES(string eNTIDAD)
        {
            var eNTIDADParameter = eNTIDAD != null ?
                new ObjectParameter("ENTIDAD", eNTIDAD) :
                new ObjectParameter("ENTIDAD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WS_OPERACIONES_Result>("WS_OPERACIONES", eNTIDADParameter);
        }
    }
}
