//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsBVRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vConsultaEmisionesWEB
    {
        public string ISIN { get; set; }
        public string CodEnSistema { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public decimal ValorNominal { get; set; }
        public string Moneda { get; set; }
        public string TipoTasa { get; set; }
        public string NombreTitulo { get; set; }
        public string BaseLiquidacion { get; set; }
        public string NombrePeriodo { get; set; }
        public Nullable<decimal> Cupon { get; set; }
        public string TipoAmortizacionCapital { get; set; }
        public string PuestoBolsaCodigos { get; set; }
        public Nullable<decimal> MontoTotalDeLaEmision { get; set; }
        public string Calificacion { get; set; }
        public string TipoEmisor { get; set; }
        public decimal Monto_Emitido { get; set; }
        public string FormaColocacionNombre { get; set; }
    }
}
