//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsBVRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vConsultaOrdenesFirme
    {
        public string Código_Local { get; set; }
        public string Código_ISIN { get; set; }
        public Nullable<System.DateTime> Fecha_de_Vencimiento { get; set; }
        public Nullable<System.DateTime> Fecha_de_Postura { get; set; }
        public string Hora { get; set; }
        public string Moneda_de_Liquidación { get; set; }
        public Nullable<decimal> Valor_Nominal_Pesos { get; set; }
        public Nullable<decimal> Valor_Nominal_Dólares { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public Nullable<decimal> Valor_Transado_Pesos { get; set; }
        public Nullable<decimal> Valor_Transado_Dólares { get; set; }
        public string Fecha_de_Modificación { get; set; }
        public Nullable<int> Mercado { get; set; }
        public string Duracion { get; set; }
        public int Secuencia { get; set; }
        public string Código_Rueda { get; set; }
        public string PosicionCompraVenta { get; set; }
        public string NroOperacionVinculada { get; set; }
    }
}
