//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsBVRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOrdenesFirmePropias
    {
        public string Nemotecnico { get; set; }
        public string ISIN { get; set; }
        public string MonedaLiquidacion { get; set; }
        public Nullable<decimal> NominalUnitario { get; set; }
        public Nullable<decimal> TasaCupon { get; set; }
        public Nullable<System.DateTime> FechaPostura { get; set; }
        public Nullable<System.TimeSpan> HoraPostura { get; set; }
        public Nullable<decimal> ValorNominal { get; set; }
        public decimal ValorTransado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Rendimiento { get; set; }
        public Nullable<System.DateTime> HoraUltimaModificacion { get; set; }
        public string PuestodeBolsa { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string CODRUEDA { get; set; }
        public string PosicionCompraVenta { get; set; }
        public string Duracion { get; set; }
        public Nullable<int> PlazoLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public string NroOperacionVinculada { get; set; }
    }
}
