//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsBVRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUsuarios
    {
        public string NOMBRE { get; set; }
        public string NOMBREENTIDAD { get; set; }
        public string SERVICIO { get; set; }
        public string TOKEN { get; set; }
        public string NOMBREENTIDADID { get; set; }
    }
}
